### ISSUE TITLE
restore_talaris_behaviour issue

### ISSUE THREAD

**Issue by gjbartlett** [Kortemme-Lab/flex_ddG_tutorial#1]
Hi - when I try to run this tutorial, I get the following error in rosetta.out:

ERROR: Option matching -restore_talaris_behaviour not found in command line top-level context

I'm using Rosetta Scripts from rosetta 3.8, any help appreciated!

Thanks,

Gail

**Comment by kylebarlow** [comment]
The tutorial was written to use a more recent version of Rosetta than 3.8, so it is recommended that you download and use "Rosetta 2017.52", or the even more recent weekly release.

Alternatively, you might be able to get the tutorial to work by removing the -restore_talaris_behavior flag, as in Rosetta 3.8, Talaris is the default score function and the flag to restore its behavior had not yet been created.

**Comment by gjbartlett** [comment]
Great, thanks for the speedy response!

All the best,

Gail

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
