### ISSUE TITLE
Change in output between Rosetta versions

### ISSUE THREAD

**Issue by coreymhudson** [Kortemme-Lab/flex_ddG_tutorial#10]
When FlexddG is run using the latest 2020 version of Rosetta the script does not return zero for DDG when the native residue is substituted for itself.  On the other hand, when FlexddG is run using the 2018 version of Rosetta (specifically 2018.48.60516) the script always returns zero for DDG when the native residue is substituted for itself.

**Comment by kylebarlow** [comment]
Thanks for the report - that is good to know for me and everyone. I am not currently using the latest 2020 version of Rosetta for this protocol, so the best way forward is to probably continue using 2018.48.60516. The protocol uses the prior Talaris energy function in any case, so there is not much to be gained by using a newer version of Rosetta.
