### ISSUE TITLE
How to mutate multiple residues together?

### ISSUE THREAD

**Issue by shengzizhang** [Kortemme-Lab/flex_ddG_tutorial#12]
I would like to use flex_ddG to perform mutations at multiple positions together, can flex_ddG do that and what is the input res_file format would be?

Thanks,

**Comment by gezmi** [comment]
Just include them all in the resfile, e.g mutating 4 residues to Ala:

10 A PIKAA A
11 A PIKAA A
15 A PIKAA A
56 A PIKAA A


https://www.rosettacommons.org/docs/latest/rosetta_basics/file_types/resfiles

**Comment by chrisxuerk226** [comment]
Hi, I was wondering what to do when I have a phosphorylated residue in my protein, like phosphorylated tyrosine?

**Comment by kylebarlow** [comment]
The answer on how to perform multiple mutations is correct, thanks!

As for the phosphorylated residue question, standard Rosetta procedures should work. If the residue isn't near the interface of interest, you can also try loading the input PDB with Rosetta's ignore unrecognized residue option:
https://www.rosettacommons.org/demos/latest/tutorials/input_and_output/input_and_output#controlling-input_dealing-with-odd-residues-and-water-molecules
