### ISSUE TITLE
Flex ddg crashes when two chains are specified to move. 

### ISSUE THREAD

**Issue by daipayans** [Kortemme-Lab/flex_ddG_tutorial#13]
Hi, 
I get the following message in `ROSETTA_CRASH.log` :

> InterfaceDdGMover needs to have chains (numbers or names) or jumps defined to move

Please advise on how to proceed. Many thanks in advance!

**Comment by kylebarlow** [comment]
One easy thing to try would be to invert the invert the chain selection - for example, if your input PDB has chains A, B & C, try specifying "C" instead of "A,B". Does that help? If not, seeing the Rosetta script and command line call you are attempting would be helpful.

**Comment by daipayans** [comment]
Hi @kylebarlow, Many thanks for the quick response. Moving single chain (for eg. "A" in my case for complex AB) to seems work ok so far. However, based on your response, I have a follow-up question, specifically related to the tutorail example  on site mutagenesis. My question is that should we move a single chain or both chains? If both chains cannot be moved during a single flex-ddG simulation, which of the two chains should we select? Thanks again for your help.

**Comment by kylebarlow** [comment]
You only want to pick a single chain to move, as this chain will be translated far away in the simulation in order to simulate the unbound state. Picking either chain works!

**Comment by daipayans** [comment]
Thanks for the explanation! I was confused based on the description in the readme for "chainstomov" wihch says "Can be a single chain as in "B" or multiple chains, as in "L,H"."
