### ISSUE TITLE
error with ddG-backrub.xml

### ISSUE THREAD

**Issue by ZHeidari** [Kortemme-Lab/flex_ddG_tutorial#21]
After running run_example_1.py I tried to run the following:
rosetta_scripts.linuxgccrelease -s 5M2O.pdb -parser:protocol ddG-backrub.xml -parser:script_vars chainstomove=B mutate_resfile_relpath=nataa_mutations.resfile number_backrub_trials=10 max_minimization_iter=5 abs_score_convergence_thresh=200.0 backrub_trajectory_stride=5  -restore_talaris_behavior -in:file:fullatom -ignore_unrecognized_res -ignore_zero_occupancy false -ex1 -ex2

I got the following error:
ERROR: Option matching -restore_talaris_behavior not found in command line top-level context

I do not have any idea whst this error means? could you please help me with this. 

FYI: I have these files in my current directory: 5M2O.pdb, nataa_mutations.resfile and ddG-backrub.xml.

Thanks

**Comment by kylebarlow** [comment]
Hi, I am guessing that more recent versions of Rosetta do not have the -restore_talaris_behavior flag. Until the protocol is updated, I'd recommend using an older release version, such as the 2018 version mentioned in the README. I have also updated the README to reflect that newer versions of Rosetta probably will not work.
