### ISSUE TITLE
ALLAA specified at a certain residue position

### ISSUE THREAD

**Issue by bioragul** [Kortemme-Lab/flex_ddG_tutorial#5]
Hello,
I am wondering how this protocol handles if I specify ALLAA for a residue position. Do we get the ddg value for 19 other amino acids or the best mutant residue for that position? When I try this I do get results but not sure if it is for the best mutant residue for that position or something else. Thanks

**Comment by kylebarlow** [comment]
The results won't work as you intend if you use ALLAA in this manner - instead I would suggest looking at the second "saturation" example I have uploaded.
