### ISSUE TITLE
issue when mutating from phosphorylated residues

### ISSUE THREAD

**Issue by ValeSora** [Kortemme-Lab/flex_ddG_tutorial#6]
Hi,
I am encountering a strange issue while trying to mutate one phosphoserine (named SEP in my PDB file as per Rosetta conventions) to alanine. Indeed, judging from Rosetta output it recognises the residue but it does not mutate it, and the mutated PDB structure that I can retrieve after running the protocol actually shows the phosphoserine at the mutation site.

This is the part of the Rosetta output where normally the mutation is logged:

`protocols.rosetta_scripts.ParsedProtocol: (0) =======================BEGIN MOVER PackRotamersMover - mutate=======================
core.pack.task: (0) Packer task: initialize from command line() 
core.pack.pack_rotamers: (0) built 0 rotamers at 0 positions.`

I am using a `nataa_mutations.resfile` written as follows (phosposerine at pos. 170 of the PDB file, chain B):

NATAA
start
170 B PIKAA A

I am running the release `rosetta-2018.33.60351` on Linux, using the MPI version of the `rosetta_scripts` binary.

Thank you in advance!

Valentina

**Comment by kylebarlow** [comment]
I don't have personal experience with non-canonical amino acids in Rosetta. If you ran your input structure through a much simpler Rosetta script that only tries to do the mutation step, I'd imagine it also wouldn't work (but this could be a good thing to check). If this is the case, then the Rosetta forums would be a good place to go to ask about how to mutate non-canonical positions.

Alternatively, you could convert that position into a regular serine before inputting it into this protocol. The wild type score might not reflect exactly what you want it to, but you could also produce a separate phosphoserine wild type score for comparison.
