### ISSUE TITLE
Missing scoring terms when value is 0

### ISSUE THREAD

**Issue by georgkempf** [Kortemme-Lab/flex_ddG_tutorial#7]
Hi,
we encountered the case where some scoring terms result in 0 according to the score.sc file. By checking our structure it seems plausible as there are no hydrogen bonds of this particular type present. It seems that scoring terms with a value of 0 are not written to the db3 file and thus are not extracted by the analyze script causing an assertion error.
Thanks

**Comment by kylebarlow** [comment]
Thanks for the update - hopefully the tracer that reports ddG from the InterfaceDdGMover in the Rosetta output might work directly, and still give you the result you want? If you were able to get the analysis script to work around this issue I'd be happy to take a pull request as well.
