### ISSUE TITLE
ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by johnnytam100** [Kortemme-Lab/flex_ddG_tutorial#8]
Hi, I successfully ran `run_example_2_saturation.py` and an `output_saturation` folder has been generated. After that, however, when I run `analyze_flex_ddG.py` using the following command, an error of "ValueError: No objects to concatenate" appeared, as follows:

` python analyze_flex_ddG.py output_saturation`

> Traceback (most recent call last):
>   File "analyze_flex_ddG.py", line 215, in <module>
>     analyze_output_folder( folder_to_analyze )
>   File "analyze_flex_ddG.py", line 190, in analyze_output_folder
>     scores = pd.concat( inner_scores_list )
>   File "/home/cltam/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 281, in concat
>     sort=sort,
>   File "/home/cltam/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 329, in __init__
>     raise ValueError("No objects to concatenate")
> ValueError: No objects to concatenate

May I know how should I make it work?
Thanks a lot!

**Comment by kylebarlow** [comment]
Thanks for the report - without seeing more of your output files, I'm not sure what's going on here. If you are still hitting this issue, upload your example output if you can. It could be that your Rosetta run failed in some way, and no output was generated.

**Comment by wangtao111111** [comment]
I also encountered this problem, please ask if this problem has been solved?

**Comment by wangtao111111** [comment]
I also encountered this situation, I moved the Rosetta folder after compiling Rosetta, so some library dependencies could not be found, I recompiled and it was fine
