### ISSUE TITLE
Protein monomer mutation ddG calculation

### ISSUE THREAD

**Issue by daipayans** [Kortemme-Lab/flex_ddG_tutorial#9]
Hi, 
Can this pipeline for a protein monomer? Or does one have to use ddG_monomer for that? Your help is appreciated!
Thanks,
Daipayan

**Comment by kylebarlow** [comment]
Hi Daipayan,

In benchmarking, this protocol did not giver better performance for protein monomer ddG calculations, so I would suggest using ddG_monomer for that application.

Best,
-Kyle
